import React, { useState, useEffect } from "react";
import { Helmet } from "react-helmet";
import { motion, AnimatePresence, useScroll, useSpring } from "framer-motion";
import { ChevronDown, ArrowUp, Maximize2, Minimize2 } from "lucide-react";
import Page from "../../components/Page";
import { useTheme } from "../../components/JUI/Theme";

const accordionData = [
  {
    title: "Basic Terminology",
    content: (
      <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
        <p>This Privacy Policy constitutes an electronic record in accordance with applicable laws and regulations. This electronic record is generated by a computer system and therefore does not require any physical or digital signatures.</p>
        <p>Little Known Planet ("Little Known Planet") values the trust placed in us by users, visitors, partners, and customers who access our website, mobile application, social media pages, and other associated platforms. We are committed to protecting the privacy and confidentiality of the information shared with us.</p>
        <p>This Privacy Policy explains how we collect, use, store, process, protect, and disclose information received from users while accessing or using our Platform and Services including Experiences, Events, Stays, Food Services, and Place recommendations.</p>
        <p>By accessing or using the Platform, users consent to the collection and use of their information in accordance with this Privacy Policy. Continued use of the Platform shall be considered as acceptance of this Privacy Policy and any future modifications made to it.</p>
        <p>Little Known Planet reserves the right to modify, update, or revise this Privacy Policy at any time without prior notice. Users are advised to review this Privacy Policy regularly for updates or changes.</p>
      </div>
    )
  },
  {
    title: "The Information Collected by Us",
    content: (
      <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
        <p>Little Known Planet may collect information provided directly by users while creating accounts, making bookings, contacting customer support, participating in activities, subscribing to updates, or using the Platform.</p>
        <p>Such information may include personal details, contact information, booking information, payment details, communication history, preferences, device information, browser information, IP address, and location details.</p>
        <p>Information may also be collected automatically through cookies, analytics tools, application usage, and system-generated logs for improving platform functionality, user experience, and security.</p>
      </div>
    )
  },
  {
    title: "Personal Information",
    content: (
      <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
        <p>Personal Information refers to information that can identify an individual user directly or indirectly.</p>
        <p>Users may voluntarily provide personal information while registering on the Platform, booking services, participating in events or experiences, submitting reviews, or communicating with the support team.</p>
        <p>Users agree that the information provided by them is accurate, complete, and up to date. Little Known Planet shall not be responsible for issues arising from incorrect, incomplete, or outdated information provided by users.</p>
        <p>Personal Information collected by the Platform shall only be used for lawful and legitimate purposes related to service delivery, operations, customer support, and business activities.</p>
      </div>
    )
  },
  {
    title: "Cookies",
    content: (
      <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
        <p>Little Known Planet may use cookies and similar tracking technologies to improve user experience, analyze platform performance, personalize content, remember preferences, and enhance security.</p>
        <p>Cookies help the Platform understand user behavior, improve navigation, and provide customized recommendations and promotional offers.</p>
        <p>Users may choose to disable cookies through browser settings; however, certain features or functionalities of the Platform may not operate properly if cookies are disabled.</p>
      </div>
    )
  },
  {
    title: "Offers and Updates",
    content: (
      <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
        <p>Little Known Planet may use user information to send booking confirmations, service-related updates, promotional offers, newsletters, event notifications, discounts, referral benefits, and marketing communications.</p>
        <p>Users may choose to opt out of promotional communications at any time through unsubscribe options or by contacting customer support.</p>
        <p>Even after opting out of promotional messages, users may continue to receive important transactional or booking-related communications.</p>
      </div>
    )
  },
  {
    title: "Use of the Information Collected by Us",
    content: (
      <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
        <p>Information collected by Little Known Planet may be used for providing services, processing bookings, verifying users, facilitating payments, improving platform functionality, personalizing user experience, conducting analytics, resolving disputes, preventing fraud, ensuring security, and complying with legal obligations.</p>
        <p>The collected information may also be used for customer support, internal business operations, service improvements, communication purposes, promotional activities, and operational analysis.</p>
        <p>Little Known Planet may use anonymized or aggregated information for research, analytics, business insights, and platform enhancement purposes.</p>
      </div>
    )
  },
  {
    title: "Sharing of Information with Third Parties",
    content: (
      <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
        <p>Little Known Planet may share user information with partners, vendors, event organizers, stay providers, restaurants, payment gateways, technology providers, customer support partners, and other authorized third parties only to the extent necessary for providing services or completing bookings.</p>
        <p>Information may also be shared with government authorities, law enforcement agencies, or legal entities where required under applicable laws or legal processes.</p>
        <p>Little Known Planet does not sell or rent personal information of users to third parties for independent marketing purposes.</p>
      </div>
    )
  },
  {
    title: "Disclosure of Information",
    content: (
      <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
        <p>Little Known Planet may disclose user information when such disclosure is necessary for complying with legal obligations, enforcing platform policies, protecting platform security, preventing fraud, responding to lawful requests, or safeguarding the rights, property, and safety of users, partners, or the Platform.</p>
        <p>Information may also be disclosed during mergers, acquisitions, restructuring, investments, or transfer of business operations.</p>
      </div>
    )
  },
  {
    title: "Protecting Your Information",
    content: (
      <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
        <p>Little Known Planet takes reasonable efforts to protect user information against unauthorized access, misuse, alteration, disclosure, or destruction.</p>
        <p>Access to personal information is restricted only to authorized employees, partners, vendors, or service providers who require such access for operational or service-related purposes.</p>
        <p>While reasonable safeguards are implemented, users acknowledge that no internet-based platform or electronic storage system can guarantee absolute security.</p>
      </div>
    )
  },
  {
    title: "Security Measures",
    content: (
      <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
        <p>The Platform uses reasonable technical, administrative, and security measures to protect user data and maintain confidentiality.</p>
        <p>Security practices may include encrypted communications, access controls, secure payment processing systems, monitoring mechanisms, and restricted data access procedures.</p>
        <p>Users are responsible for maintaining the confidentiality of their account credentials, passwords, and login details.</p>
        <p>Little Known Planet shall not be responsible for unauthorized access caused due to user negligence, third-party attacks, or circumstances beyond reasonable control.</p>
      </div>
    )
  },
  {
    title: "Applicable Law and Jurisdiction",
    content: (
      <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
        <p>This Privacy Policy shall be governed and interpreted in accordance with the laws of India.</p>
        <p>Any disputes arising in connection with this Privacy Policy shall be subject to the exclusive jurisdiction of the courts located in the city/state where Little Known Planet operates its registered office.</p>
      </div>
    )
  },
  {
    title: "Changes to this Privacy Policy",
    content: (
      <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
        <p>Little Known Planet reserves the right to modify, update, amend, or revise this Privacy Policy at any time without prior notice.</p>
        <p>Updated versions of the Privacy Policy shall become effective immediately upon publication on the Platform.</p>
        <p>Users are encouraged to periodically review this Privacy Policy to stay informed about how information is collected and used.</p>
        <p>Continued use of the Platform after any modifications shall constitute acceptance of the updated Privacy Policy.</p>
      </div>
    )
  },
  {
    title: "Grievance Policy",
    content: (
      <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
        <p>Users may contact the support or grievance team regarding privacy concerns, data-related issues, unauthorized access, correction requests, complaints, or other concerns related to personal information.</p>
        <p>Little Known Planet will make reasonable efforts to address and resolve grievances within a reasonable timeframe in accordance with applicable laws and operational procedures.</p>
      </div>
    )
  },
  {
    title: "Special Note About Minors",
    content: (
      <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
        <p>Users below the age of eighteen (18) years should use the Platform only under the supervision and consent of a parent or legal guardian.</p>
        <p>Little Known Planet does not knowingly collect personal information from minors without appropriate authorization.</p>
        <p>If any information relating to minors is identified without valid consent, reasonable efforts may be taken to remove such information from the Platform records.</p>
      </div>
    )
  },
  {
    title: "Using Mobile Phones and Tablet Apps",
    content: (
      <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
        <p>Users accessing the Platform through mobile phones, tablets, or mobile applications acknowledge that certain information such as device information, app usage details, operating system data, network information, and approximate location details may be collected for improving platform performance, user experience, security, and operational functionality.</p>
        <p>Standard mobile carrier charges, data usage charges, or internet charges may apply while using the Platform on mobile devices.</p>
      </div>
    )
  },
  {
    title: "Express Consent",
    content: (
      <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
        <p>By accessing, browsing, registering, booking, or using the Little Known Planet Platform, users expressly consent to the collection, storage, processing, usage, and disclosure of information in accordance with this Privacy Policy.</p>
        <p>Users also consent to receiving communications including emails, calls, SMS, WhatsApp messages, push notifications, booking updates, support communications, and promotional messages from Little Known Planet or its authorized partners.</p>
        <p>Continued use of the Platform shall constitute express acceptance of this Privacy Policy and related platform policies.</p>
      </div>
    )
  }
];

const AccordionItem = ({ item, isOpen, onClick, themeTokens }) => {
  const { FG, M, B, A, BG } = themeTokens;
  const [isHovered, setIsHovered] = useState(false);

  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: "-50px" }}
      transition={{ duration: 0.5, ease: "easeOut" }}
      style={{ 
        marginBottom: "16px",
        borderRadius: "12px",
        border: isOpen ? `1px solid rgba(0, 151, 178, 0.4)` : `1px solid ${B}`,
        boxShadow: isOpen ? "0 4px 20px rgba(0, 151, 178, 0.08)" : (isHovered ? "0 4px 12px rgba(0,0,0,0.03)" : "none"),
        overflow: "hidden",
        background: isOpen ? BG : (isHovered ? "rgba(0,0,0,0.02)" : BG),
        transition: "all 0.3s ease"
      }}
    >
      <button
        onClick={onClick}
        onMouseEnter={() => setIsHovered(true)}
        onMouseLeave={() => setIsHovered(false)}
        style={{
          width: "100%",
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          padding: "24px 32px",
          background: "transparent",
          border: "none",
          cursor: "pointer",
          textAlign: "left",
          outline: "none"
        }}
      >
        <span style={{ fontSize: "clamp(1.1rem, 2vw, 1.3rem)", fontWeight: isOpen ? 600 : 500, color: isOpen ? A : FG, transition: "color 0.3s ease" }}>
          {item.title}
        </span>
        <motion.div
          animate={{ rotate: isOpen ? 180 : 0 }}
          transition={{ duration: 0.3, ease: [0.22, 1, 0.36, 1] }}
          style={{ display: "flex", alignItems: "center", justifyContent: "center", color: isOpen ? A : M }}
        >
          <ChevronDown size={22} strokeWidth={isOpen ? 2 : 1.5} />
        </motion.div>
      </button>
      <AnimatePresence initial={false}>
        {isOpen && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.4, ease: [0.22, 1, 0.36, 1] }}
          >
            <div style={{ padding: "0px 32px 32px 32px", color: M, fontSize: "1.1rem", lineHeight: 1.9 }}>
              {item.content}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
};

const PrivacyPolicy = () => {
  const { tokens } = useTheme();
  const [openIndices, setOpenIndices] = useState([0]);
  const [showTopBtn, setShowTopBtn] = useState(false);
  const { scrollYProgress } = useScroll();
  const scaleX = useSpring(scrollYProgress, {
    stiffness: 100,
    damping: 30,
    restDelta: 0.001
  });

  useEffect(() => {
    window.scrollTo({ top: 0, behavior: 'smooth' });
    const handleScroll = () => {
      if (window.scrollY > 400) {
        setShowTopBtn(true);
      } else {
        setShowTopBtn(false);
      }
    };
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  const goToTop = () => {
    window.scrollTo({
      top: 0,
      behavior: "smooth",
    });
  };

  const toggleAccordion = (index) => {
    if (openIndices.includes(index)) {
      setOpenIndices(openIndices.filter(i => i !== index));
    } else {
      setOpenIndices([...openIndices, index]);
    }
  };

  const expandAll = () => {
    setOpenIndices(accordionData.map((_, i) => i));
  };

  const collapseAll = () => {
    setOpenIndices([]);
  };

  return (
    <Page>
      <Helmet>
        <title>Privacy Policy | Little Known Planet</title>
        <meta name="description" content="Review the Privacy Policy for using Little Known Planet services." />
      </Helmet>
      
      {/* Top Progress Bar */}
      <motion.div
        style={{
          position: "fixed",
          top: 0,
          left: 0,
          right: 0,
          height: "4px",
          background: tokens.A,
          transformOrigin: "0%",
          scaleX,
          zIndex: 9999
        }}
      />

      <div style={{ background: tokens.BG, minHeight: "100vh", paddingTop: "140px", paddingBottom: "120px", color: tokens.FG }}>
        <div style={{ maxWidth: "860px", margin: "0 auto", padding: "0 24px" }}>
          
          <motion.div 
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, ease: "easeOut" }}
            style={{ textAlign: "center", marginBottom: "60px" }}
          >
            <h1 className="font-display" style={{ 
              fontSize: "clamp(3.5rem, 7vw, 5.5rem)", 
              fontWeight: 400, 
              color: tokens.A, 
              letterSpacing: "-0.02em",
              marginBottom: "24px",
              fontFamily: "Georgia, serif"
            }}>
              Privacy Policy
            </h1>
            <p style={{ fontSize: "1.1rem", color: tokens.M, maxWidth: "600px", margin: "0 auto", lineHeight: 1.6 }}>
              How we collect, use, and protect your information.
              Last updated: May 2026.
            </p>
            
          </motion.div>

          <div style={{ display: "flex", flexDirection: "column" }}>
            {accordionData.map((item, index) => (
              <AccordionItem
                key={index}
                item={item}
                isOpen={openIndices.includes(index)}
                onClick={() => toggleAccordion(index)}
                themeTokens={tokens}
              />
            ))}
          </div>

        </div>
      </div>

      {/* Floating Back to Top Button */}
      <AnimatePresence>
        {showTopBtn && (
          <motion.button
            initial={{ opacity: 0, scale: 0.8 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.8 }}
            onClick={goToTop}
            style={{
              position: "fixed",
              bottom: "40px",
              right: "40px",
              width: "50px",
              height: "50px",
              borderRadius: "50%",
              background: "rgba(255, 255, 255, 0.85)",
              backdropFilter: "blur(12px)",
              WebkitBackdropFilter: "blur(12px)",
              border: `1px solid rgba(0, 151, 178, 0.2)`,
              color: tokens.A,
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              cursor: "pointer",
              boxShadow: "0 8px 32px rgba(0, 0, 0, 0.1)",
              zIndex: 1000,
              transition: "transform 0.2s ease"
            }}
            whileHover={{ y: -5, boxShadow: "0 12px 40px rgba(0, 151, 178, 0.15)" }}
            whileTap={{ scale: 0.95 }}
          >
            <ArrowUp size={24} strokeWidth={2} />
          </motion.button>
        )}
      </AnimatePresence>
    </Page>
  );
};

export default PrivacyPolicy;
